# Generated by Django 4.2.6 on 2023-10-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=255)),
                ('district', models.CharField(default='', max_length=255)),
                ('market', models.CharField(default='', max_length=255)),
                ('commodity', models.CharField(default='', max_length=255)),
                ('variety', models.CharField(default='', max_length=255)),
                ('grade', models.CharField(default='', max_length=255)),
                ('arrival_date', models.CharField(default='', max_length=255)),
                ('min_price', models.CharField(default='', max_length=255)),
                ('max_price', models.CharField(default='', max_length=255)),
                ('modal_price', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.BigIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
